[workspace]
resolver = "2"
members = [
    "program",
    "script",
    "shared"
]

[workspace.package]
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
arbitrary = "1.1.3"
alloy = { version = "0.2.1", features = ["contract", "json", "providers", "signer-local", "signers", "sol-types", "network"] }
alloy-primitives = "0.7.7"
alloy-sol-types = "0.7.7"
anyhow = "1.0.86"
derivative = "2.2.0"
ethereum_hashing = "0.6.0"
ethereum_serde_utils = "0.5.2"
ethereum_ssz = "0.5.4"
ethereum_ssz_derive = "0.5.4"
ethereum-types = {version = "0.14.1", features = ["arbitrary"] }
hex = "0.4.3"
hex-literal = "0.4.1"
itertools = "0.13.0"
log = "0.4.21"
proptest = "1.0.0"
proptest-arbitrary-interop = "0.1.0"
reqwest = "0.12.7"
rs_merkle = "1.4.2"
serde = { version = "1.0", default-features = false, features = ["derive"] }
serde_derive = "1.0.204"
serde_json = { version = "1.0", default-features = false, features = ["alloc"] }
simple_logger = "5.0.0"
sp1-core-machine = "3.0.0"
sp1-derive = "3.0.0"
sp1-helper = "3.0.0"
sp1-sdk = "3.0.0"
sp1-zkvm = "3.0.0"
ssz_types = { version = "0.6.0", features = ["arbitrary"] }
tokio = "1.39.2"
tracing = "0.1.40"
tree_hash = "0.6.0"
tree_hash_derive = "0.6.0"
typenum = "1.17.0"

[workspace.devDependencies]
cargo-license = "0.6.1"
cargo-bundle-licenses = "2.0.0"

[patch.crates-io]
sha2-v0-10-8 = { git = "https://github.com/sp1-patches/RustCrypto-hashes", package = "sha2", branch = "patch-sha2-v0.10.8" }
ethereum_hashing = { git = "https://github.com/sp1-patches/ethereum_hashing", branch = "v0.6.0" }