[package]
version.workspace = true
edition.workspace = true
license.workspace = true
name = "sp1-lido-accounting-zk-lib-merkle-tree-leaves-derive"

[lib]
proc-macro = true

[dependencies]
syn = "2.0"
quote = "1.0"
