[package]
version.workspace = true
edition.workspace = true
license.workspace = true
name = "sp1_lido_accounting_zk_lib_merkle_tree_leaves_derive"

[lib]
proc-macro = true

[dependencies]
syn = "2.0"
quote = "1.0"
