[workspace]
[package]
version = "0.1.0"
name = "sp1-lido-accounting-zk-script"
edition = "2021"
default-run = "prove"

[[bin]]
name = "prove"
path = "src/bin/prove.rs"

[[bin]]
name = "pre-deploy"
path = "src/bin/pre_deploy.rs"

[lib]
name = "sp1_lido_accounting_scripts"
path = "src/lib/lib.rs"

[dependencies]
sp1-sdk = { git = "https://github.com/succinctlabs/sp1.git", tag="v1.1.0", features = [ "network" ] }
serde_json = { version = "1.0", default-features = false, features = ["alloc"] }
serde = { version = "1.0", default-features = false, features = ["derive"] }
clap = { version = "4.0", features = ["derive", "env"] }
tracing = "0.1.40"
alloy-sol-types = "0.7.7"
log = "0.4.21"
hex-literal = "0.4.1"
hex = "0.4"
anyhow = "1.0.86"
sp1_lido_accounting_zk_shared = { path = "../shared", features = ["reqwest"] }
tokio = "1.39.2"
tree_hash = "0.6.0"
alloy-primitives = "0.7.7"

[build-dependencies]
sp1-helper = { git = "https://github.com/succinctlabs/sp1.git", tag="v1.1.0" }
