[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.27"
fs_permissions = [
    { access = "read-write", path = "./" },
    { access = "read", path = "../temp" }
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
