[workspace]
[package]
version = "0.1.0"
name = "sp1-lido-accounting-zk-shared"
edition = "2021"

[lib]
name = "sp1_lido_accountin_zk_shared"
path = "src/lib/lib.rs"

[[bin]]
name = "ssz_e2e_test"
path = "src/bin/ssz_e2e_test.rs"
required-features = ["synthetic"]

[[bin]]
name = "report_e2e_test"
path = "src/bin/report.rs"
required-features = ["synthetic"]

[dependencies]
serde_json = { version = "1.0", default-features = false, features = ["alloc"] }
serde = { version = "1.0", default-features = false, features = ["derive"] }
alloy-sol-types = "0.7.2"
log = "0.4.21"
anyhow = "1.0.86"
ethereum_ssz = "0.5.4"
ethereum_serde_utils = "0.5.2"
ethereum_ssz_derive = "0.5.4"
simple_logger = "5.0.0"
tokio = { version = "1.38.0", features = ["full"] }
ssz_types = "0.6.0"
ethereum-types = "0.14.1"
serde_derive = "1.0.204"
hex = "0.4.3"
tree_hash_derive = "0.6.0"
tree_hash = "0.6.0"

[features]
synthetic = []
