[package]
version.workspace = true
edition.workspace = true
license.workspace = true
name = "sp1-lido-accounting-zk-program"

[dependencies]
alloy-sol-types.workspace = true
sp1-derive.workspace = true
sp1-zkvm.workspace = true
sp1_lido_accounting_zk_shared = { path = "../shared" }
tree_hash.workspace = true
