[workspace]
[package]
version = "0.1.0"
name = "sp1-lido-accounting-zk-program"
edition = "2021"

[dependencies]
alloy-sol-types = "0.7.2"
sp1-derive = "1.1.0"
sp1-zkvm = { git = "https://github.com/succinctlabs/sp1.git", tag="v1.0.5-testnet" }
sp1_lido_accounting_zk_shared = { path = "../shared" }


[patch.crates-io]
sha2-v0-10-8 = { git = "https://github.com/sp1-patches/RustCrypto-hashes", package = "sha2", branch = "patch-sha2-v0.10.8" }
ethereum_hashing = { path = "../../../ethereum_hashing" }
